name: Build_project_with_lints&tests
on: 
  push:
    branches: 
      - dev
jobs:
  build:
   runs-on: windows-latest
   steps:
     - name: Copy code
     - uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
         architecture: x64   
     - name: Cache Gradle
       uses: actions/cache@v2
       with:
         path: ~/.gradle/caches
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
         restore-keys: ${{ runner.os }}-gradle 
     - name: Drop Files
       run: del /q app\build\reports && rd /q /s app\build\reports\ktlint 
     - name: Check_lints&tests 
       run: gradlew app:build 
